# Form implementation generated from reading ui file 'd:\WangQianyu\Workspace\VideoAnnotation\progress.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProgressDialog(object):
    def setupUi(self, ProgressDialog):
        ProgressDialog.setObjectName("ProgressDialog")
        ProgressDialog.setMinimumSize(QtCore.QSize(300, 100))
        ProgressDialog.setMaximumSize(QtCore.QSize(300, 100))
        self.progress_bar = QtWidgets.QProgressBar(parent=ProgressDialog)
        self.progress_bar.setGeometry(QtCore.QRect(10, 10, 280, 23))
        self.progress_bar.setMinimum(0)
        self.progress_bar.setMaximum(100)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")

        self.retranslateUi(ProgressDialog)
        QtCore.QMetaObject.connectSlotsByName(ProgressDialog)

    def retranslateUi(self, ProgressDialog):
        _translate = QtCore.QCoreApplication.translate
        ProgressDialog.setWindowTitle(_translate("ProgressDialog", "Progress"))
